name: weather forecast ci

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-dotnet-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: WebApplication1

      - name: build app
        run: dotnet build -c Release --no-restore
        working-directory: WebApplication1

      - name: run test
        run: dotnet test -c Release --no-build --verbosity normal
        working-directory: WeatherForecastTests
        
      - name: dotnet publish
        run: dotnet publish WebApplication1.csproj -c Release -o ./dotnet-app
        working-directory: WebApplication1
        
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: WebApplication1/dotnet-app