name: weather forecast staging cd

on:
  workflow_run:
    workflows: ["weather forecast ci"]
    types:
      - completed

jobs:
  deploy-to-staging-webapp:
    if: >
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact from build job
        uses: artifact/download-artifact@v5
        with:
          name: dotnet-app